# Generated by Django 4.2.16 on 2024-10-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagecontent',
            name='work_img',
            field=models.ImageField(default='', upload_to='img/main_page/', verbose_name='Картинка с работой'),
        ),
    ]
