# Generated by Django 4.2.16 on 2024-10-20 13:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_mainpagecontent_work_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpagecontent',
            name='description',
            field=tinymce.models.HTMLField(default='Немного о себе'),
        ),
    ]
